name: Hello world
description: "Greet someone"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.hoanggggf.outputs.random-number}}
runs:
  using: "composite"
  steps:
    - name: Set greeting message
      run: echo "Hello $INPUT_WHO_TO_GREET!"
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Generate a random number
      id: hoangggff
      run: echo "random-number=$((RANDOM % 100))" >> "$GITHUB_OUTPUT"
      shell: bash
