version: "3"

tasks:
    generate-version:
        desc: Generate version for a service
        vars:
            SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
        cmds:
            - |
              set -euo pipefail
              TAG=$(git describe --tags --always --first-parent --match "{{.SERVICE_RELEASE_TAG}}@[0-9]*.[0-9]*.[0-9]*")
              PREFIX="{{.SERVICE_RELEASE_TAG}}@"
              echo "${TAG#${PREFIX}}"
        silent: true

    generate-version-tag:
        desc: Generate image tag for a service
        vars:
            SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
            VERSION:
                sh: task -s generate-version -- {{.SERVICE_RELEASE_TAG}}
        cmds:
            - |
              echo "{{.SERVICE_RELEASE_TAG}}:{{.VERSION}}"
