name: Caching
on:
  workflow_dispatch:

jobs:
  action-cache:
    name: Prime cache demo
    runs-on: ubuntu-22.04
    steps:
      - name: Restore cache
        id: demo-cache
        uses: actions/cache@v3
        with:
          path: demo-cache
          key: ${{ runner.os }}-demo-cache

      - name: Populate cache directory
        if: steps.demo-cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss, populating cache directory"
          mkdir -p demo-cache
          date >  demo-cache/timestamp.txt

      - name: Save cache
        if: steps.demo-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: demo-cache
          key: ${{ runner.os }}-demo-cache

      - name: verify cache status
        run: |
          echo "cache-hit? -> ${{steps.demo-cache.outcome.cache-hit}}"
          cat demo-cache/timestamp.txt

  node-cache:
    name: npm dependency cache (setup-demo)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: node-caching

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: node-caching/package-lock.json
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: List first few modules
        run: ls -R node_modules | head -n 10
